{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled3.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "mount_file_id": "12NjOAd4monBECF4-Xfto2H1PnkOrnNmv",
      "authorship_tag": "ABX9TyOJSiDWFUUX51hnWztCzrt7",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/munkhbato/gcolab/blob/master/Untitled4.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "X-Iyqj7j7cx_",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 0
        },
        "outputId": "47ec7148-4d46-45b4-f513-a649143a205f"
      },
      "source": [
        "!scrapy crawl spidey"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/usr/local/lib/python3.6/dist-packages/scrapy/extensions/feedexport.py:239: ScrapyDeprecationWarning: The `FEED_URI` and `FEED_FORMAT` settings have been deprecated in favor of the `FEEDS` setting. Please see the `FEEDS` setting docs for more details\n",
            "  exporter = cls(crawler)\n",
            "2020-08-11 14:41:14 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.edusearchindia.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.edusearchindia.org.\n",
            "2020-08-11 14:41:15 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.edusearchindia.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.edusearchindia.org.\n",
            "2020-08-11 14:41:29 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.taaleem.edu.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.taaleem.edu.in.\n",
            "2020-08-11 14:41:29 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.taaleem.edu.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.taaleem.edu.in.\n",
            "2020-08-11 14:41:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://dishaschool.ac.in/admission_process.php> (failed 3 times): DNS lookup failed: no results for hostname lookup: dishaschool.ac.in.\n",
            "2020-08-11 14:41:36 [scrapy.core.scraper] ERROR: Error downloading <GET http://dishaschool.ac.in/admission_process.php>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: dishaschool.ac.in.\n",
            "2020-08-11 14:41:38 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://istm.org.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: istm.org.in.\n",
            "2020-08-11 14:41:38 [scrapy.core.scraper] ERROR: Error downloading <GET https://istm.org.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: istm.org.in.\n",
            "2020-08-11 14:42:09 [scrapy.core.downloader.handlers.http11] WARNING: Expected response size (81128039) larger than download warn size (33554432) in request <GET https://admission.davchd.ac.in/Downloads/DAV-10%20%20PDF%20(25-07-2020).pdf?Id=1127Gak32iWQpdpbFiqM0fMuRKKK1xnZYOFn3kVESwQkFA=>.\n",
            "2020-08-11 14:42:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://admission.davchd.ac.in/downloads/hostel2020.pdf?Id=133sWs0dMBjh7cS2wF5v0f+cFyI781nhpjr7WqawoEG6Nk=> (referer: https://davchd.ac.in/)\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/content/email_collecter/email_collecter/spiders/spidey.py\", line 98, in parse_page\n",
            "    emails.extend(self.extract_emails_xp(response, domain) or [])\n",
            "  File \"/content/email_collecter/email_collecter/spiders/spidey.py\", line 143, in extract_emails_xp\n",
            "    email_elems = response.xpath('//a[contains(@href, \"mailto:\")]')\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/http/response/__init__.py\", line 120, in xpath\n",
            "    raise NotSupported(\"Response content isn't text\")\n",
            "scrapy.exceptions.NotSupported: Response content isn't text\n",
            "2020-08-11 14:42:14 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://iibmstab-Franchise-E.org/contact-2/#nquiry> (failed 3 times): DNS lookup failed: no results for hostname lookup: iibmstab-Franchise-E.org.\n",
            "2020-08-11 14:42:14 [scrapy.core.scraper] ERROR: Error downloading <GET http://iibmstab-Franchise-E.org/contact-2/#nquiry>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: iibmstab-Franchise-E.org.\n",
            "2020-08-11 14:42:21 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.aura.edu.in/regular/about_aura.html> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.aura.edu.in.\n",
            "2020-08-11 14:42:21 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.aura.edu.in/regular/about_aura.html>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.aura.edu.in.\n",
            "2020-08-11 14:42:27 [scrapy.core.downloader.handlers.http11] WARNING: Received more bytes than download warn size (33554432) in request <GET https://admission.davchd.ac.in/Downloads/DAV-10%20%20PDF%20(25-07-2020).pdf?Id=1127Gak32iWQpdpbFiqM0fMuRKKK1xnZYOFn3kVESwQkFA=>.\n",
            "2020-08-11 14:42:27 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://admission.sgtbkhalsadu.ac.in> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:28 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.niilm-cms.edu.in/admission/fee-structure-scholarships/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.niilm-cms.edu.in.\n",
            "2020-08-11 14:42:28 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.niilm-cms.edu.in/admission/fee-structure-scholarships/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.niilm-cms.edu.in.\n",
            "2020-08-11 14:42:31 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://odmeducation.org/index.php> (failed 3 times): DNS lookup failed: no results for hostname lookup: odmeducation.org.\n",
            "2020-08-11 14:42:31 [scrapy.core.scraper] ERROR: Error downloading <GET http://odmeducation.org/index.php>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: odmeducation.org.\n",
            "2020-08-11 14:42:32 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/about-us/leadership-team/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:32 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.iiasmconsultants.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.iiasmconsultants.com.\n",
            "2020-08-11 14:42:33 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.iiasmconsultants.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.iiasmconsultants.com.\n",
            "2020-08-11 14:42:33 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/about-us/presence/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:33 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/about-us/strategic-alliances/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:34 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/about-us/success-stories-testimonials/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:35 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/about-us/awards-recognition/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/contacts/career-at-safeducate/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.safeducate.com/contacts/employee-login/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://erosimt.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: erosimt.org.\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.nimsr.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.nimsr.org.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://erosimt.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: erosimt.org.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.nimsr.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.nimsr.org.\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.wlci.in/colleges-india/mumbai-campus-location.aspx> (failed 3 times): An error occurred while connecting: 113: No route to host.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.wlci.in/colleges-india/mumbai-campus-location.aspx>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "twisted.internet.error.ConnectError: An error occurred while connecting: 113: No route to host.\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.successpath.co.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.successpath.co.in.\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.sparknidea.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.sparknidea.com.\n",
            "2020-08-11 14:42:37 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.ipee.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.ipee.in.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.successpath.co.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.successpath.co.in.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.sparknidea.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.sparknidea.com.\n",
            "2020-08-11 14:42:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.ipee.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.ipee.in.\n",
            "2020-08-11 14:42:38 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://kapsinstitute.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: kapsinstitute.com.\n",
            "2020-08-11 14:42:38 [scrapy.core.scraper] ERROR: Error downloading <GET http://kapsinstitute.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: kapsinstitute.com.\n",
            "2020-08-11 14:42:38 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.saaranshgroup.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.saaranshgroup.com.\n",
            "2020-08-11 14:42:38 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.saaranshgroup.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.saaranshgroup.com.\n",
            "2020-08-11 14:42:38 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.asianretailinstitute.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.asianretailinstitute.com.\n",
            "2020-08-11 14:42:38 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.asianretailinstitute.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.asianretailinstitute.com.\n",
            "2020-08-11 14:42:38 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://universalinstituteindia.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: universalinstituteindia.com.\n",
            "2020-08-11 14:42:38 [scrapy.core.scraper] ERROR: Error downloading <GET http://universalinstituteindia.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: universalinstituteindia.com.\n",
            "2020-08-11 14:42:39 [scrapy.core.scraper] ERROR: Error downloading <GET https:///www.auston.edu.sg/about-us/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py\", line 55, in mustbe_deferred\n",
            "    result = f(*args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/__init__.py\", line 76, in download_request\n",
            "    return handler.download_request(request, spider)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/http11.py\", line 88, in download_request\n",
            "    return agent.download_request(request)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/http11.py\", line 354, in download_request\n",
            "    d = agent.request(method, to_bytes(url, encoding='ascii'), headers, bodyproducer)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/web/client.py\", line 1738, in request\n",
            "    endpoint = self._getEndpoint(parsedURI)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/web/client.py\", line 1721, in _getEndpoint\n",
            "    return self._endpointFactory.endpointForURI(uri)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/web/client.py\", line 1596, in endpointForURI\n",
            "    uri.port)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/contextfactory.py\", line 63, in creatorForNetloc\n",
            "    verbose_logging=self.tls_verbose_logging)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/tls.py\", line 50, in __init__\n",
            "    super(ScrapyClientTLSOptions, self).__init__(hostname, ctx)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/_sslverify.py\", line 1174, in __init__\n",
            "    self._hostnameBytes = _idnaBytes(hostname)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/_idna.py\", line 30, in _idnaBytes\n",
            "    return idna.encode(text)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/idna/core.py\", line 357, in encode\n",
            "    raise IDNAError('Empty domain')\n",
            "idna.core.IDNAError: Empty domain\n",
            "2020-08-11 14:42:40 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://onjobtraining.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: onjobtraining.in.\n",
            "2020-08-11 14:42:40 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.sitmm.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.sitmm.com.\n",
            "2020-08-11 14:42:40 [scrapy.core.scraper] ERROR: Error downloading <GET http://onjobtraining.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: onjobtraining.in.\n",
            "2020-08-11 14:42:40 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.sitmm.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.sitmm.com.\n",
            "2020-08-11 14:42:42 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.autuseducation.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.autuseducation.in.\n",
            "2020-08-11 14:42:42 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.autuseducation.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.autuseducation.in.\n",
            "2020-08-11 14:42:42 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.amityglobalvarsity.com/Home/About#aboutpartner1> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.nimsr-edu.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.nimsr-edu.com.\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://educationalsociety.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: educationalsociety.org.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.nimsr-edu.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.nimsr-edu.com.\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.merieducation.net/> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.alaskaindia.co.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.alaskaindia.co.in.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://educationalsociety.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: educationalsociety.org.\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.dpaacademyofeducation.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.dpaacademyofeducation.com.\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.appintraining.com/delhi_pitampura/information-security-ethical-hacking/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.appintraining.com.\n",
            "2020-08-11 14:42:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.tripsteracademy.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.tripsteracademy.in.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.alaskaindia.co.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.alaskaindia.co.in.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.dpaacademyofeducation.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.dpaacademyofeducation.com.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.appintraining.com/delhi_pitampura/information-security-ethical-hacking/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.appintraining.com.\n",
            "2020-08-11 14:42:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.tripsteracademy.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.tripsteracademy.in.\n",
            "2020-08-11 14:43:20 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.rimsonweb.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.rimsonweb.com.\n",
            "2020-08-11 14:43:20 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.rimsonweb.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.rimsonweb.com.\n",
            "2020-08-11 14:43:20 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.valueeducation.co.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.valueeducation.co.in.\n",
            "2020-08-11 14:43:21 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.valueeducation.co.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.valueeducation.co.in.\n",
            "2020-08-11 14:43:21 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.rimat.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.rimat.org.\n",
            "2020-08-11 14:43:21 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.rimat.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.rimat.org.\n",
            "2020-08-11 14:43:25 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.erosimt.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.erosimt.org.\n",
            "2020-08-11 14:43:26 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.erosimt.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.erosimt.org.\n",
            "2020-08-11 14:43:27 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.ihsmranchi.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.ihsmranchi.in.\n",
            "2020-08-11 14:43:27 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.ihsmranchi.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.ihsmranchi.in.\n",
            "2020-08-11 14:43:28 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://www.ddekuk.ac.in/about_us.php> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:43:30 [scrapy.core.scraper] ERROR: Error downloading <GET %20https://www.iitism.ac.in/index.php/pages/about_history>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py\", line 55, in mustbe_deferred\n",
            "    result = f(*args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/__init__.py\", line 75, in download_request\n",
            "    (scheme, self._notconfigured[scheme]))\n",
            "scrapy.exceptions.NotSupported: Unsupported URL scheme '': no handler available for that scheme\n",
            "2020-08-11 14:43:30 [scrapy.core.scraper] ERROR: Error downloading <GET %20https://www.iitism.ac.in/index.php/pages/about_administration>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py\", line 55, in mustbe_deferred\n",
            "    result = f(*args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/__init__.py\", line 75, in download_request\n",
            "    (scheme, self._notconfigured[scheme]))\n",
            "scrapy.exceptions.NotSupported: Unsupported URL scheme '': no handler available for that scheme\n",
            "2020-08-11 14:43:30 [scrapy.core.scraper] ERROR: Error downloading <GET %20https://www.iitism.ac.in/index.php/pages/about_overview>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py\", line 55, in mustbe_deferred\n",
            "    result = f(*args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/handlers/__init__.py\", line 75, in download_request\n",
            "    (scheme, self._notconfigured[scheme]))\n",
            "scrapy.exceptions.NotSupported: Unsupported URL scheme '': no handler available for that scheme\n",
            "2020-08-11 14:43:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://www.ddekuk.ac.in/contact.php> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:43:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://www.ddekuk.ac.in/about_1.php> (failed 3 times): 500 Internal Server Error\n",
            "2020-08-11 14:44:41 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://indiaeducation.ernet.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: indiaeducation.ernet.in.\n",
            "2020-08-11 14:44:41 [scrapy.core.scraper] ERROR: Error downloading <GET http://indiaeducation.ernet.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: indiaeducation.ernet.in.\n",
            "2020-08-11 14:44:44 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.csrcoe.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.csrcoe.in.\n",
            "2020-08-11 14:44:44 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://smibs.edu.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: smibs.edu.in.\n",
            "2020-08-11 14:44:44 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.csrcoe.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.csrcoe.in.\n",
            "2020-08-11 14:44:44 [scrapy.core.scraper] ERROR: Error downloading <GET http://smibs.edu.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: smibs.edu.in.\n",
            "2020-08-11 14:44:46 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.snsvo7.seekandsource.com/rkinstituteofmanagement/home.html> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.snsvo7.seekandsource.com.\n",
            "2020-08-11 14:44:46 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.snsvo7.seekandsource.com/rkinstituteofmanagement/home.html>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.snsvo7.seekandsource.com.\n",
            "2020-08-11 14:44:50 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.wlci.in/> (failed 3 times): An error occurred while connecting: 113: No route to host.\n",
            "2020-08-11 14:44:50 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.wlci.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "twisted.internet.error.ConnectError: An error occurred while connecting: 113: No route to host.\n",
            "2020-08-11 14:44:50 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.gsbedu.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.gsbedu.org.\n",
            "2020-08-11 14:44:50 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.smei-india.org/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.smei-india.org.\n",
            "2020-08-11 14:44:50 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.gsbedu.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.gsbedu.org.\n",
            "2020-08-11 14:44:50 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.inspiregec.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.inspiregec.com.\n",
            "2020-08-11 14:44:50 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://unityinstitute.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: unityinstitute.in.\n",
            "2020-08-11 14:44:50 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.smei-india.org/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.smei-india.org.\n",
            "2020-08-11 14:44:51 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.inspiregec.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.inspiregec.com.\n",
            "2020-08-11 14:44:51 [scrapy.core.scraper] ERROR: Error downloading <GET http://unityinstitute.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: unityinstitute.in.\n",
            "2020-08-11 14:44:51 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.ksoumysore.edu.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.ksoumysore.edu.in.\n",
            "2020-08-11 14:44:51 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.ksoumysore.edu.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.ksoumysore.edu.in.\n",
            "2020-08-11 14:44:52 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://aptechcalicut.blogspot.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: aptechcalicut.blogspot.in.\n",
            "2020-08-11 14:44:52 [scrapy.core.scraper] ERROR: Error downloading <GET http://aptechcalicut.blogspot.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: aptechcalicut.blogspot.in.\n",
            "2020-08-11 14:45:08 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.army.gov.in/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.army.gov.in.\n",
            "2020-08-11 14:45:08 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.ceyeindia.com/> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.ceyeindia.com.\n",
            "2020-08-11 14:45:08 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.army.gov.in/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.army.gov.in.\n",
            "2020-08-11 14:45:08 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.ceyeindia.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 1416, in _inlineCallbacks\n",
            "    result = result.throwExceptionIntoGenerator(g)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py\", line 512, in throwExceptionIntoGenerator\n",
            "    return g.throw(self.type, self.value, self.tb)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n",
            "    current.result = callback(current.result, *args, **kw)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py\", line 982, in startConnectionAttempts\n",
            "    \"no results for hostname lookup: {}\".format(self._hostStr)\n",
            "twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.ceyeindia.com.\n",
            "2020-08-11 14:45:11 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.bridgesom.com/> (failed 3 times): TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:11 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://eshiksa.apnamshop.com/contact/> (failed 3 times): TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:11 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET http://www.mipseducation.com/> (failed 3 times): TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:12 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.bridgesom.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "twisted.internet.error.TCPTimedOutError: TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:12 [scrapy.core.scraper] ERROR: Error downloading <GET http://eshiksa.apnamshop.com/contact/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "twisted.internet.error.TCPTimedOutError: TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:12 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.mipseducation.com/>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py\", line 44, in process_request\n",
            "    return (yield download_func(request=request, spider=spider))\n",
            "twisted.internet.error.TCPTimedOutError: TCP connection timed out: 110: Connection timed out.\n",
            "2020-08-11 14:45:19 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for hostname \"www.vsit.edu.in\"; VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'www.vsit.edu.in'))])\n",
            "2020-08-11 14:45:21 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for hostname \"www.vsit.edu.in\"; VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'www.vsit.edu.in'))])\n",
            "2020-08-11 14:45:21 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for hostname \"www.vsit.edu.in\"; VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'www.vsit.edu.in'))])\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}